stages:
  - automation_tests
  - build

Automation Testing:
  image: tmaier/docker-compose:latest
  stage: automation_tests
  services:
    - docker:dind
  before_script:
    - docker-compose build
    - docker-compose up &
    - sleep 20s
  script:
    #- docker ps
    #- docker exec mlaas-phase-1_web_1 sh -c "python -m unittest tests"
    - echo "Testing Yet to Be Done"
  only:
    - development

Building & Pushing Docker Images:
  image: docker:latest
  stage: build
  services:
    - docker:dind

  variables:
    #? Naming the Image:  Image_name:modulename-time_of_commit-commit_hash
    DB_IMAGE: $CI_REGISTRY_IMAGE:db-$CI_COMMIT_TIMESTAMP-$CI_COMMIT_SHORT_SHA
    DB_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:db-latest
    MS_IMAGE: $CI_REGISTRY_IMAGE:ms-$CI_COMMIT_TIMESTAMP-$CI_COMMIT_SHORT_SHA
    MS_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:ms-latest
    WEB_IMAGE: $CI_REGISTRY_IMAGE:web-$CI_COMMIT_TIMESTAMP-$CI_COMMIT_SHORT_SHA
    WEB_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:web-latest

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # Building DB Image
    - echo "Building Database Image"
    - cd DB
    - string_one = $DB_RELEASE_IMAGE
    - string_two = $DB_IMAGE
    - string_one = ${string_one,,}
    - string_two = ${string_two,,}
    - docker pull $string_one || true
    - docker build --cache-from $string_one --tag $string_two --tag $string_one .
    - docker push $string_two
    - docker push $string_one
    - cd ..
    
    # Building Micro-Service Image 
    - echo "Building Micro-Service Image"
    - cd MS
    - string_one = $MS_RELEASE_IMAGE
    - string_two = $MS_IMAGE
    - string_one = ${string_one,,}
    - string_two = ${string_two,,}
    - docker pull $string_one || true
    - docker build --cache-from $string_one --tag $string_two --tag $string_one .
    - docker push $string_two
    - docker push $string_one
    - cd ..

    # Building Web Image
    - echo "Building Web Image"
    - cd Web
    - string_one = $WEB_RELEASE_IMAGE
    - string_two = $WEB_IMAGE
    - string_one = ${string_one,,}
    - string_two = ${string_two,,}
    - docker pull $string_one || true
    - docker build --cache-from $string_one --tag $string_two --tag $string_one .
    - docker push $string_two
    - docker push $string_one
    - cd ..

  only:
    - master
