version: '3.7'
services:

    postgres:                                           # create postgres container
        build: ./DB
        hostname: postgresql
        container_name: postgres_container
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    airflow:                                            # create airflow container
        build: './airflow'                       # construct the container along the Dockerfile in this folder
        container_name: airflow_container
        restart: always
        depends_on:
            - postgres           
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:                                        # mount the following local folders
            - ./MS/mlaas:/usr/local/airflow/dags
            - ./MS/mlaas/mlruns:/usr/local/airflow/mlruns
        ports:
            - "8080:8080"                               # expose port
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    web:                                             # create a MLFlow container
        build: './MS' 
        container_name: ms_container
        #command: bash -c "mlflow server --backend-store-uri ./mlflow --host 0.0.0.0 --port 5400 && python manage.py runserver 0.0.0.0:8000" # construct the container along the Dockerfile in this folder
        command: python manage.py runserver 0.0.0.0:8000 
        volumes: 
            - "./MS/mlaas:/mlaas"
        ports:
            #- "5400:5400" 
            - "8000:8000"
        links:
            - postgres
        depends_on:
            - mlflow
            - airflow

    mlflow:
        build: './MS'
        #command: mlflow server --backend-store-uri ./mlflow --host 0.0.0.0 --port 5400
        command: mlflow server --backend-store-uri postgresql://airflow:airflow@postgresql:5432/airflow?options=-csearch_path%3Ddbo,mlaas --default-artifact-root file:///mlaas/mlruns --host 0.0.0.0 --port 5400
        volumes: 
            - "./MS/mlaas:/mlaas"
        ports:
            - "5400:5400"
        links:
            - postgres
        depends_on:
            - postgres

    # angular:
    #     build: './Web'
    #     ports:
    #     - "4200:4200"
    #     volumes: 
    #     - "/app/node_modules"
    #     - "./Web:/app"
    #     depends_on:
    #     - web

volumes:
    postgres_data:
