version: '3.7'
services:

  postgres:
    image: registry.gitlab.com/isgtest/end-to-end-p1:db-latest
    hostname: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow:
    image: registry.gitlab.com/isgtest/end-to-end-p1:af-latest
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    ports:
      - "8080:8080"                               # expose port
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  web:
    image: registry.gitlab.com/isgtest/end-to-end-p1:ms-latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - mlflow

  mlflow:
    image: registry.gitlab.com/isgtest/end-to-end-p1:ms-latest
    command: mlflow server --backend-store-uri postgresql://airflow:airflow@postgresql:5432/airflow --default-artifact-root file:///mlaas/mlruns --host 0.0.0.0 --port 5400
    ports:
      - "5400:5400"
    depends_on:
      - postgres

  angular:
    image: registry.gitlab.com/isgtest/end-to-end-p1:web-latest
    ports:
      - "4200:4200"
    depends_on:
      - web
     
  
      
  

volumes:
  postgres_data:


networks:
  backend:
    driver: "bridge"