#Create image based on the official Node 6 image from dockerhub
FROM node:12.18.1-alpine as build-step

# Create a directory where our app will be placed
#RUN mkdir -p /angular

# Change directory so that our commands run inside this new directory
WORKDIR /app

# Copy dependency definitions
# COPY package.json ./

# # Install dependecies
# RUN npm install
# #RUN npm install -g @angular/cli@10.2.0

# #RUN npm run build --prod

# # Get all the code needed to run the app
# COPY . .

# # Expose the port the app runs in
# EXPOSE 4200

# # Serve the app
# #CMD ["npm", "start"]
# CMD npm run start
